# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8af874ca75f73835b59e21343e2c0df341014f547ac41b4d7858d00ac634fcd1c03cf3616b615de05d5c86a0d71f6f2f345ed3783c3c65e84ea4e47930c1e8c5

test:
  secret_key_base: b782da5ab9f5be6a4b5c0e987b5ad6ba0fd8fe8f4bfff6a4c633dcb21577835d7eeab337510b813bf56482a04ddf8f3d77e9a2c267bab621327d83d60214158a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
